---
- hosts: test
  become: yes
  vars:
    root_path: "~/tv_app"
    repot: https://github.com/IDRISSHACKER/jenkins_ansible_test.git
    user_look: "{{ lookup('env', 'USER') }}"
  
  roles:
    - repo
  
...
